# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        name: ${{ matrix.os }} (py ${{ matrix.version }}${{ matrix.special }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: False
            matrix:
                os: [ubuntu-latest]
                version: ["3.9"]

        steps:
            -   uses: actions/checkout@v2

            -   name: Cancel Previous Runs
                uses: styfle/cancel-workflow-action@0.9.1
                with:
                    access_token: ${{ github.token }}

            -   name: Set up Python ${{ matrix.version }} on ${{ matrix.os }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.version }}

            -   name: Setup CP2K 8.2
                env:
                    TEST: "${{ secrets.TEST }}"
                run: |
                    case "${{ steps.load-ams.outputs.cache-hit }}" in
                        "true")
                            echo 1
                            ;;
                        *)
                            echo 0
                            ;;
                    esac
