# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        name: ${{ matrix.os }} (py ${{ matrix.python-version }}${{ matrix.special }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: False
            matrix:
                os: [ubuntu-latest]
                python-version: [3.9]

        steps:
            -   uses: actions/checkout@v2

            -   name: Cancel Previous Runs
                uses: styfle/cancel-workflow-action@0.9.1
                with:
                    access_token: ${{ github.token }}

            -   name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}

            -   name: Setup CP2K 8.2
                run: |
                    git clone git+https://github.com/cp2k/cp2k@v8.2.0
                    mkdir cp2k/bin
                    wget https://github.com/cp2k/cp2k/releases/download/v8.2.0/cp2k-8.2-Linux-x86_64.ssmp --directory-prefix="$PWD/cp2k/bin"
                    export PATH=$PATH:"$PWD/cp2k/bin"
                    export CP2K_DATA_DIR="$PWD/cp2k/data"
